from typing import Final
from kivy.metrics import dp

__all__ = (
    "SNAP_ANIM_DURATION",
    "QUICK_ANIM_DURATION",
    "SLOW_ANIM_DURATION",
    "RAIL_ITEM_HOLDER_DEFAULT_WIDTH",
    "SEPARATOR_DEFAULT_LINE_THICKNESS",
)


SNAP_ANIM_DURATION: Final = .15
QUICK_ANIM_DURATION: Final = .45
SLOW_ANIM_DURATION: Final = 1
RAIL_ITEM_HOLDER_DEFAULT_WIDTH: Final = dp(90)
SEPARATOR_DEFAULT_LINE_THICKNESS: Final = dp(1)
